name: CI
on:
  push:
    paths-ignore:
    - 'resources/**'
    - 'README.md'

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for cpp programs.
      uses: arvsrao/clang-format-action@master
  test-project:
    name: Test Project
    needs: formatting-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test project with googletest.
      uses: arvsrao/googletest-action@master
